module.exports = {
    "automaticRearrangeAfterDropNode": true,
    // "nodeHighlightBehavior": true,
    "collapsible": false,
    "directed": true,
    "focusAnimationDuration": 0.75,
    "focusZoom": 1,
    "freezeAllDragEvents": false,
    "height": 900,
    "highlightDegree": 1,
    "highlightOpacity": 0.2,
    "linkHighlightBehavior": true,
    "maxZoom": 8,
    "minZoom": 0.1,
    "initialZoom": 0.6,
    "nodeHighlightBehavior": false,
    "panAndZoom": false,
    "staticGraph": false,
    "staticGraphWithDragAndDrop": false,
    "width": window.innerWidth,
    "d3": {
      "alphaTarget": 0.05,
      "gravity": -175,
      "linkLength": 100,
      "linkStrength": 2,
      "disableLinkForce": false
    },
    "node": {
      // "color": "#83D32D",
      "showToolTip": true,
      "fontColor": "black",
      "fontSize": 10,
      "fontWeight": "normal",
      // "highlightColor": "red",
      // "highlightFontSize": 14,
      // "highlightFontWeight": "bold",
      // "highlightStrokeColor": "red",
      "highlightStrokeWidth": 1.5,
      "labelPosition": "",
      "mouseCursor": "crosshair",
      "opacity": 1,
      "renderLabel": true,
      "size": 200,
      "strokeColor": "none",
      "strokeWidth": 0.5,
      "svg": "",
      "symbolType": "circle",
      "viewGenerator": null
    },
    "link": {
      "color": "#c2d8d9",
      // "color": "black",
      "highlightColor": "lightblue",
      "labelProperty": "label",
      "mouseCursor": "pointer",
      "opacity": 1,
      "renderLabel": true,
      "semanticStrokeWidth": true,
      "strokeWidth": 3,
      "markerHeight": 5,
      "markerWidth": 5,
      "type": "STRAIGHT",
      "selfLinkDirection": "TOP_RIGHT",
      "strokeDasharray": 0,
      "strokeDashoffset": 0,
      "strokeLinecap": "butt",
      "type": "STRAIGHT"
    }
  }