# Generated by Django 4.0.5 on 2023-05-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_tb_survey_settings_tb_survey_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='data',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='survey',
            name='extras',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='survey',
            name='processed_data',
            field=models.JSONField(default=dict),
        ),
    ]
